{
 "title": "DIAL Project insights",
 "tags": [
  "DIAL",
  "ai-dial-analytics-realtime",
  "Aggregated data"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb" },
   { "name": "INFLUX_BUCKET", "query": "buckets()" },
   { "name": "Show_Top1_percent", "query": "No, Yes" }
  ]
 },
 "panels": [
  {
   "title": "Deployment/Model Stats Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n      |> filter(fn: (r) => (r._field == \"prompt_tokens\" or r._field == \"request_count\" or r._field == \"price\" ) )\r\n         |> filter(fn: (r) => exists r.project_id)\r\n    |> schema.fieldsAsCols()\r\n    |> group(columns: [\"project_id\", \"deployment\", \"model\"])\r\n    |> reduce(\r\n        fn: (r, accumulator) => ({\r\n          request_count: getOrDefault(f: r.request_count, d: 0) + accumulator.request_count,\r\n          prompt_tokens: getOrDefault(f: r.prompt_tokens, d: 0) + accumulator.prompt_tokens,\r\n          price: getOrDefault(f: r.price, d: 0.0) + accumulator.price\r\n        }),\r\n        identity: {request_count: 0, prompt_tokens: 0, price:0.0}\r\n    )\r\n\r\n    data_request\r\n    |> group()\r\n    |> sort(columns: [\"request_count\"], desc: true)"
    }
   ]
  },
  {
   "title": "Reqests share by deciles of Project in chat",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"request_count\" and r.project_id !=\"\" )\r\n  |> schema.fieldsAsCols()\r\n  |> group(columns: [\"project_id\"])\r\n  |> sum(column:\"request_count\")\r\n|>group()\r\n\r\n  // Sort users by total_requests in descending order\r\nsorted_users = data_request\r\n  |> sort(columns: [\"request_count\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n\r\n// Calculate percentile thresholds\r\npercentile_90_user = sorted_users |> quantile(column: \"rowId\", q: 0.9) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_80_user = sorted_users |> quantile(column: \"rowId\", q: 0.8) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_70_user = sorted_users |> quantile(column: \"rowId\", q: 0.7) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_60_user = sorted_users |> quantile(column: \"rowId\", q: 0.6) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_50_user = sorted_users |> quantile(column: \"rowId\", q: 0.5) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_40_user = sorted_users |> quantile(column: \"rowId\", q: 0.4) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_30_user = sorted_users |> quantile(column: \"rowId\", q: 0.3) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_20_user = sorted_users |> quantile(column: \"rowId\", q: 0.2) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_10_user = sorted_users |> quantile(column: \"rowId\", q: 0.1) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_01_user = sorted_users |> quantile(column: \"rowId\", q: 0.01) |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n\r\n// Map percentiles to each user based on request count thresholds\r\ndeterminePercentiles = (sorted_users, topUsers) => \r\n  if topUsers == \"No\" then\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          request_count: r.request_count,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else \"Top 10%\"\r\n      }))\r\n  else\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          request_count: r.request_count,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else if r.rowId >= percentile_01_user.rowId then \"91-99%\"\r\n                      else \"Top 1%\"\r\n      }))\r\n\r\n// Define the bucket and call the function\r\ntopUsers = \"${Show_Top1_percent}\" // Replace with your actual bucket variable\r\npercentiles = determinePercentiles(sorted_users: sorted_users, topUsers: topUsers)\r\n\r\n// Count the number of users in each percentile\r\npercentile_data =\r\npercentiles\r\n  |> group(columns: [\"percentile_user\"])\r\n   |> sum(column: \"request_count\")\r\n    |> map(fn: (r) => ({r with join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n|> group()\r\ntotal_cost_data = percentiles\r\n\r\n   |> sum(column: \"request_count\")\r\n     |> map(fn: (r) => ({total_request_count: r.request_count, join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n   cross_joined_data = join(\r\n  tables: {percentile: percentile_data, total: total_cost_data},\r\n on: [\"join_key\"]\r\n)\r\n |> map(fn: (r) => ({\r\n\r\n      percent_of_request: float(v: r.request_count) / float(v: r.total_request_count)*100.0,   \r\n      percentile_user: r.percentile_user,\r\n      sort: if r.percentile_user == \"0-10%\" then \"0\"\r\n                  else if r.percentile_user == \"11-20%\" then \"1\"\r\n                  else if r.percentile_user == \"21-30%\" then \"2\"\r\n                  else if r.percentile_user == \"31-40%\" then \"3\"\r\n                  else if r.percentile_user == \"41-50%\" then \"4\"\r\n                  else if r.percentile_user == \"51-60%\" then \"5\"\r\n                  else if r.percentile_user == \"61-70%\" then \"6\"\r\n                  else if r.percentile_user == \"71-80%\" then \"7\"\r\n                  else if r.percentile_user == \"81-90%\" then \"8\"\r\n                  else if r.percentile_user == \"91-99%\" then \"9\"\r\n                  else \"99\"\r\n  }))\r\ncross_joined_data\r\n|>group()\r\n|> sort(columns: [\"sort\"], desc: true)\r\n  "
    }
   ]
  },
  {
   "title": "Reqests share by deciles of Project in chat",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 10, "y": 13 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"request_count\" and r.project_id !=\"\" and r.project_id !=\"undefined\" )\r\n    |> schema.fieldsAsCols()\r\n |> group(columns: [\"project_id\"])\r\n  |> sum(column:\"request_count\")\r\n\r\n|>group()\r\n\r\n  // Sort users by total_requests in descending order\r\nsorted_users = data_request\r\n  |> sort(columns: [\"request_count\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n\r\n// Calculate percentile thresholds\r\npercentile_90_user = sorted_users |> quantile(column: \"rowId\", q: 0.9) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_80_user = sorted_users |> quantile(column: \"rowId\", q: 0.8) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_70_user = sorted_users |> quantile(column: \"rowId\", q: 0.7) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_60_user = sorted_users |> quantile(column: \"rowId\", q: 0.6) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_50_user = sorted_users |> quantile(column: \"rowId\", q: 0.5) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_40_user = sorted_users |> quantile(column: \"rowId\", q: 0.4) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_30_user = sorted_users |> quantile(column: \"rowId\", q: 0.3) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_20_user = sorted_users |> quantile(column: \"rowId\", q: 0.2) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_10_user = sorted_users |> quantile(column: \"rowId\", q: 0.1) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_01_user = sorted_users |> quantile(column: \"rowId\", q: 0.01) |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n\r\n// Map percentiles to each user based on request count thresholds\r\ndeterminePercentiles = (sorted_users, topUsers) => \r\n  if topUsers == \"No\" then\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          request_count: r.request_count,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else \"Top 10%\"\r\n      }))\r\n  else\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          request_count: r.request_count,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else if r.rowId >= percentile_01_user.rowId then \"91-99%\"\r\n                      else \"Top 1%\"\r\n      }))\r\n// Define the bucket and call the function\r\ntopUsers = \"${Show_Top1_percent}\" // Replace with your actual bucket variable\r\npercentiles = determinePercentiles(sorted_users: sorted_users, topUsers: topUsers)\r\n// Count the number of users in each percentile\r\npercentile_data =\r\npercentiles\r\n  |> group(columns: [\"percentile_user\"])\r\n   |> sum(column: \"request_count\")\r\n    |> map(fn: (r) => ({r with join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n|> group()\r\ntotal_cost_data = percentiles\r\n\r\n   |> sum(column: \"request_count\")\r\n     |> map(fn: (r) => ({total_request_count: r.request_count, join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n   cross_joined_data = join(\r\n  tables: {percentile: percentile_data, total: total_cost_data},\r\n on: [\"join_key\"]\r\n)\r\n |> map(fn: (r) => ({percent_of_request: float(v: r.request_count) / float(v: r.total_request_count)*100.0,\r\n     \r\n        request_count:r.request_count,\r\n        Percentile_user: r.percentile_user,\r\n        sort: if r.percentile_user == \"0-10%\" then \"0\"\r\n                  else if r.percentile_user == \"11-20%\" then \"1\"\r\n                  else if r.percentile_user == \"21-30%\" then \"2\"\r\n                  else if r.percentile_user == \"31-40%\" then \"3\"\r\n                  else if r.percentile_user == \"41-50%\" then \"4\"\r\n                  else if r.percentile_user == \"51-60%\" then \"5\"\r\n                  else if r.percentile_user == \"61-70%\" then \"6\"\r\n                  else if r.percentile_user == \"71-80%\" then \"7\"\r\n                  else if r.percentile_user == \"81-90%\" then \"8\"\r\n                  else if r.percentile_user == \"91-99%\" then \"9\"\r\n                  else \"99\"\r\n  }))\r\ncross_joined_data\r\n|>group()\r\n     |> rename(columns: {\"percent_of_request\": \"Percent of request\", \"request_count\": \"Request count\"})\r\n|> sort(columns: [\"sort\"], desc: true)\r\n|> drop(columns: [\"sort\"])"
    }
   ]
  },
  {
   "title": "Top 10 Projects by Request count",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 13 },
   "repeat": "Show_by",
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"request_count\" and r.project_id !=\"\" and r.project_id !=\"undefined\" )\r\n    |> schema.fieldsAsCols()\r\n |> group(columns: [\"project_id\"])\r\n  |> sum(column:\"request_count\")\r\n\r\n|>group()\r\n\r\n  // Sort users by total_requests in descending order\r\ndata_request\r\n  |> sort(columns: [\"request_count\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n  |> filter(fn: (r) =>  r.rowId < 11)\r\n     |> rename(columns: {\"request_count\": \"Request count\", \"project_id\": \"Project\"})\r\n      |> drop(columns: [\"rowId\"])"
    }
   ]
  },
  {
   "title": "Cost share by deciles of Project in chat",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"cost\" and r.project_id !=\"\" )\r\n    |> schema.fieldsAsCols()\r\n |> group(columns: [\"project_id\"])\r\n  |> sum(column:\"cost\")\r\n\r\n|>group()\r\n\r\n  // Sort users by total_requests in descending order\r\nsorted_users = data_request\r\n  |> sort(columns: [\"cost\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n\r\n// Calculate percentile thresholds\r\npercentile_90_user = sorted_users |> quantile(column: \"rowId\", q: 0.9) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_80_user = sorted_users |> quantile(column: \"rowId\", q: 0.8) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_70_user = sorted_users |> quantile(column: \"rowId\", q: 0.7) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_60_user = sorted_users |> quantile(column: \"rowId\", q: 0.6) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_50_user = sorted_users |> quantile(column: \"rowId\", q: 0.5) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_40_user = sorted_users |> quantile(column: \"rowId\", q: 0.4) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_30_user = sorted_users |> quantile(column: \"rowId\", q: 0.3) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_20_user = sorted_users |> quantile(column: \"rowId\", q: 0.2) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_10_user = sorted_users |> quantile(column: \"rowId\", q: 0.1) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_01_user = sorted_users |> quantile(column: \"rowId\", q: 0.01) |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n// Map percentiles to each user based on request count thresholds\r\ndeterminePercentiles = (sorted_users, topUsers) => \r\n  if topUsers == \"No\" then\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          cost: r.cost,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else \"Top 10%\"\r\n      }))\r\n  else\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          cost: r.cost,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else if r.rowId >= percentile_01_user.rowId then \"91-99%\"\r\n                      else \"Top 1%\"\r\n      }))\r\n\r\n// Define the bucket and call the function\r\ntopUsers = \"${Show_Top1_percent}\" // Replace with your actual bucket variable\r\npercentiles = determinePercentiles(sorted_users: sorted_users, topUsers: topUsers)\r\n\r\n// Count the number of users in each percentile\r\npercentile_data =\r\npercentiles\r\n  |> group(columns: [\"percentile_user\"])\r\n   |> sum(column: \"cost\")\r\n    |> map(fn: (r) => ({r with join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n|> group()\r\ntotal_cost_data = percentiles\r\n\r\n   |> sum(column: \"cost\")\r\n     |> map(fn: (r) => ({total_cost: r.cost, join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n   cross_joined_data = join(\r\n  tables: {percentile: percentile_data, total: total_cost_data},\r\n on: [\"join_key\"]\r\n)\r\n |> map(fn: (r) => ({percent_of_request:  r.cost / r.total_cost *100.0,\r\n     \r\n   percentile_user: r.percentile_user,\r\n\r\n      sort: if r.percentile_user == \"0-10%\" then \"0\"\r\n                  else if r.percentile_user == \"11-20%\" then \"1\"\r\n                  else if r.percentile_user == \"21-30%\" then \"2\"\r\n                  else if r.percentile_user == \"31-40%\" then \"3\"\r\n                  else if r.percentile_user == \"41-50%\" then \"4\"\r\n                  else if r.percentile_user == \"51-60%\" then \"5\"\r\n                  else if r.percentile_user == \"61-70%\" then \"6\"\r\n                  else if r.percentile_user == \"71-80%\" then \"7\"\r\n                  else if r.percentile_user == \"81-90%\" then \"8\"\r\n                  else if r.percentile_user == \"91-99%\" then \"9\"\r\n                  else \"99\"\r\n  }))\r\ncross_joined_data\r\n|>group()\r\n  |> sort(columns: [\"sort\"], desc: true)\r\n  "
    }
   ]
  },
  {
   "title": "Cost share by deciles of Project in chat",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 10, "y": 26 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"cost\" and r.project_id !=\"\" and r.project_id !=\"undefined\" )\r\n  |> schema.fieldsAsCols()\r\n  |> group(columns: [\"project_id\"])\r\n  |> sum(column: \"cost\")\r\n  |>group()\r\n\r\n  // Sort users by total_requests in descending order\r\nsorted_users = data_request\r\n  |> sort(columns: [\"cost\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n\r\n// Calculate percentile thresholds\r\npercentile_90_user = sorted_users |> quantile(column: \"rowId\", q: 0.9) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_80_user = sorted_users |> quantile(column: \"rowId\", q: 0.8) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_70_user = sorted_users |> quantile(column: \"rowId\", q: 0.7) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_60_user = sorted_users |> quantile(column: \"rowId\", q: 0.6) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_50_user = sorted_users |> quantile(column: \"rowId\", q: 0.5) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_40_user = sorted_users |> quantile(column: \"rowId\", q: 0.4) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_30_user = sorted_users |> quantile(column: \"rowId\", q: 0.3) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_20_user = sorted_users |> quantile(column: \"rowId\", q: 0.2) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_10_user = sorted_users |> quantile(column: \"rowId\", q: 0.1) |> findRecord(fn: (key) => true, idx: 0)\r\npercentile_01_user = sorted_users |> quantile(column: \"rowId\", q: 0.01) |> findRecord(fn: (key) => true, idx: 0)\r\n\r\n\r\n// Map percentiles to each user based on request count thresholds\r\ndeterminePercentiles = (sorted_users, topUsers) => \r\n  if topUsers == \"No\" then\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          cost: r.cost,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else \"Top 10%\"\r\n      }))\r\n  else\r\n    sorted_users\r\n      |> map(fn: (r) => ({\r\n          cost: r.cost,\r\n          rowId: r.rowId,\r\n          percentile_user: if r.rowId >= percentile_90_user.rowId then \"0-10%\"\r\n                      else if r.rowId >= percentile_80_user.rowId then \"11-20%\"\r\n                      else if r.rowId >= percentile_70_user.rowId then \"21-30%\"\r\n                      else if r.rowId >= percentile_60_user.rowId then \"31-40%\"\r\n                      else if r.rowId >= percentile_50_user.rowId then \"41-50%\"\r\n                      else if r.rowId >= percentile_40_user.rowId then \"51-60%\"\r\n                      else if r.rowId >= percentile_30_user.rowId then \"61-70%\"\r\n                      else if r.rowId >= percentile_20_user.rowId then \"71-80%\"\r\n                      else if r.rowId >= percentile_10_user.rowId then \"81-90%\"\r\n                      else if r.rowId >= percentile_01_user.rowId then \"91-99%\"\r\n                      else \"Top 1%\"\r\n      }))\r\n\r\n// Define the bucket and call the function\r\ntopUsers = \"${Show_Top1_percent}\" // Replace with your actual bucket variable\r\npercentiles = determinePercentiles(sorted_users: sorted_users, topUsers: topUsers)\r\n\r\n\r\n// Count the number of users in each percentile\r\npercentile_data =\r\npercentiles\r\n  |> group(columns: [\"percentile_user\"])\r\n   |> sum(column: \"cost\")\r\n    |> map(fn: (r) => ({r with join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n|> group()\r\ntotal_cost_data = percentiles\r\n\r\n   |> sum(column: \"cost\")\r\n     |> map(fn: (r) => ({total_cost: r.cost, join_key: \"cross_join\"})) // Adding a dummy key for joining\r\n\r\n   cross_joined_data = join(\r\n  tables: {percentile: percentile_data, total: total_cost_data},\r\n on: [\"join_key\"]\r\n)\r\n |> map(fn: (r) => ({percent_of_request: float(v: r.cost) / float(v: r.total_cost)*100.0,\r\n     \r\n        cost:r.cost,\r\n        Percentile_user: r.percentile_user,\r\n        sort: if r.percentile_user == \"0-10%\" then \"0\"\r\n                  else if r.percentile_user == \"11-20%\" then \"1\"\r\n                  else if r.percentile_user == \"21-30%\" then \"2\"\r\n                  else if r.percentile_user == \"31-40%\" then \"3\"\r\n                  else if r.percentile_user == \"41-50%\" then \"4\"\r\n                  else if r.percentile_user == \"51-60%\" then \"5\"\r\n                  else if r.percentile_user == \"61-70%\" then \"6\"\r\n                  else if r.percentile_user == \"71-80%\" then \"7\"\r\n                  else if r.percentile_user == \"81-90%\" then \"8\"\r\n                  else if r.percentile_user == \"91-99%\" then \"9\"\r\n                  else \"99\"\r\n  }))\r\ncross_joined_data\r\n|>group()\r\n |> rename(columns: {\"percent_of_request\": \"Percent of Cost\", \"cost\": \"Cost($)\"})\r\n|> sort(columns: [\"sort\"], desc: true)\r\n|> drop(columns: [\"sort\"])"
    }
   ]
  },
  {
   "title": "Top 10 Projects by Cost",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"cost\" and r.project_id !=\"\" and r.project_id !=\"undefined\" )\r\n    |> schema.fieldsAsCols()\r\n |> group(columns: [\"project_id\"])\r\n  |> sum(column:\"cost\")\r\n\r\n|>group()\r\n\r\n  // Sort users by total_requests in descending order\r\ndata_request\r\n  |> sort(columns: [\"cost\"], desc: true)\r\n  |> map(fn: (r) => ({r with rowId: 1}))\r\n  // Taking the cumulative sum gives sequential values 1,2,3,4 et...\r\n  |> cumulativeSum(columns: [\"rowId\"])\r\n  |> filter(fn: (r) =>  r.rowId < 11)\r\n     |> rename(columns: { \"project_id\": \"Project\",\"cost\": \"Cost($)\"})\r\n      |> drop(columns: [\"rowId\"])"
    },
    {}
   ]
  },
  {
   "title": "Distribution of messages length in tokens",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\ndata_request = from(bucket: \"default_agg_topic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.user_type == \"project\" and \r\n   ( r._field == \"class_1\" or r._field == \"class_2\" or r._field == \"class_3\" or r._field == \"class_4\" or r._field == \"class_5\" or r._field == \"class_6\")\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: r._value,\r\n      classification: if r._field == \"class_1\" then \"> 50000\"\r\n                  else if r._field == \"class_2\" then \"10001 - 50000\"\r\n                  else if r._field == \"class_3\" then \"5001 - 10000\"\r\n                  else if r._field == \"class_4\" then \"1001 - 5000\"\r\n                  else if r._field == \"class_5\" then \"101 - 1000\"\r\n                  else \"< 101\",\r\n      sorting: if r._field == \"class_1\" then \"1\"\r\n                  else if r._field == \"class_2\" then \"2\"\r\n                  else if r._field == \"class_3\" then \"3\"\r\n                  else if r._field == \"class_4\" then \"4\"\r\n                  else if r._field == \"class_5\" then \"5\"\r\n                  else \"6\"\r\n  }))\r\n |>group(columns: [\"classification\",\"sorting\"])\r\n   |>sum(column: \"_value\")\r\n   |> map(fn: (r) => ({join_col: \"key\",\r\n                        _value: r._value,\r\n                        sorting: r.sorting,\r\n                        classification: r.classification\r\n\r\n   }))\r\n   |>group()\r\n\r\n\r\nsum_tokens = data_request\r\n     |>sum(column: \"_value\")\r\n     |> map(fn: (r) => ({join_col: \"key\",\r\n                          total_tokens: r._value\r\n     }))\r\n\r\ncross_joined_data = join(\r\n  tables: {tokens: data_request, total: sum_tokens},\r\n on: [\"join_col\"]\r\n)\r\ncross_joined_data\r\n  \r\n     |> map(fn: (r) => ({\r\n   percent_of_prompt_tokens: float(v: r._value)/float(v: r.total_tokens)*100.0, \r\n    classification: r.classification,\r\n     sorting: r.sorting\r\n     \r\n     })) \r\n     |> sort(columns: [\"sorting\"], desc: true)"
    }
   ]
  },
  {
   "title": "Distribution of messages length in tokens",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_topic\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.user_type == \"project\" and  \r\n ( r._field == \"class_1\" or r._field == \"class_2\" or r._field == \"class_3\" or r._field == \"class_4\" or r._field == \"class_5\" or r._field == \"class_6\")\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: r._value,\r\n      classification: if r._field == \"class_1\" then \"> 50000\"\r\n                  else if r._field == \"class_2\" then \"10001 - 50000\"\r\n                  else if r._field == \"class_3\" then \"5001 - 10000\"\r\n                  else if r._field == \"class_4\" then \"1001 - 5000\"\r\n                  else if r._field == \"class_5\" then \"101 - 1000\"\r\n                  else \"< 101\",\r\n      sorting: if r._field == \"class_1\" then \"1\"\r\n                  else if r._field == \"class_2\" then \"2\"\r\n                  else if r._field == \"class_3\" then \"3\"\r\n                  else if r._field == \"class_4\" then \"4\"\r\n                  else if r._field == \"class_5\" then \"5\"\r\n                  else \"6\"\r\n  }))\r\n   |>group(columns: [\"classification\",\"sorting\"])\r\n   |>sum(column: \"_value\")\r\n   |> map(fn: (r) => ({join_col: \"key\",\r\n                        prompt_tokens: r._value,\r\n                        sorting: r.sorting,\r\n                        classification: r.classification\r\n\r\n   }))\r\n   |>group()\r\n\r\n\r\nsum_tokens = data_request\r\n     |>sum(column: \"prompt_tokens\")\r\n     |> map(fn: (r) => ({join_col: \"key\",\r\n                          total_tokens: r.prompt_tokens\r\n     }))\r\n\r\ncross_joined_data = join(\r\n  tables: {tokens: data_request, total: sum_tokens},\r\n on: [\"join_col\"]\r\n)\r\ncross_joined_data\r\n  \r\n     |> map(fn: (r) => ({\r\n   percent_of_prompt_tokens: float(v: r.prompt_tokens)/float(v: r.total_tokens)*100.0, \r\n    classification: r.classification,\r\n     sorting: r.sorting,\r\n    prompt_tokens: r.prompt_tokens\r\n     \r\n     })) \r\n     |> rename(columns: {\"percent_of_prompt_tokens\": \"Percent of messages\", \"prompt_tokens\": \"Number of messages\"})\r\n     |> sort(columns: [\"sorting\"], desc: false)\r\n      |> drop(columns: [\"sorting\"])"
    }
   ]
  },
  {
   "title": "Distribution of Cost (user/project)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"cost\")\r\n  |> map(fn: (r) => ({ \r\n      r with \r\n      user_type: if r.user_hash == \"undefined\" then \"project\" else \"user\"\r\n  })) \r\n  |> group(columns: [\"user_type\"]) // Group by the new column\r\n  |> sum(column: \"_value\") // Sum cost within the groups\r\n \r\n  data_request\r\n  |>group()"
    }
   ]
  },
  {
   "title": "Distribution of Requests (user/project)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"experimental\"\r\nimport \"array\"\r\n\r\ngetOrDefault = (f, d) => if exists f then f else d\r\n\r\n// Aggregate request counts per group\r\ndata_request = from(bucket: \"default_agg_kpi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"request_count\")\r\n  |> map(fn: (r) => ({ \r\n      r with \r\n      user_type: if r.user_hash == \"undefined\" then \"project\" else \"user\"\r\n  })) \r\n  |> group(columns: [\"user_type\"]) // Group by the new column\r\n  |> sum(column: \"_value\") // Sum cost within the groups\r\n \r\n  data_request\r\n  |>group()"
    }
   ]
  }
 ]
}